version: '3.9'

services:
  hr-api:
    container_name: ${HR_API_DOCKER_COMPOSE_CONTAINER_NAME}
    image: ${HR_API_DOCKER_COMPOSE_IMAGE_NAME}
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "50053:50053"
    volumes:
      - ./.env:/app/.env
